name: "Setup beplus Git"
description: "Configure Git for the GitHub Actions runner"
inputs:
  BE_RELEASE_GITHUB_APP_ID:
    description: "GitHub App ID"
    required: true
  BE_RELEASE_GITHUB_APP_PRIVATE_KEY:
    description: "GitHub App private key"
    required: true
  BE_RELEASE_GITHUB_APP_NAME:
    description: "Name of the GitHub App to generate token for"
    required: false
    default: "beplus-release-bot"

runs:
  using: "composite"
  steps:
    - name: Generate GitHub App Token
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ inputs.BE_RELEASE_GITHUB_APP_ID }}
        private-key: ${{ inputs.BE_RELEASE_GITHUB_APP_PRIVATE_KEY }}

    - name: Configure Git
      shell: bash
      env:
        GITHUB_APP_TOKEN: ${{ steps.app-token.outputs.token }}
      run: |
        git config user.name "${{ inputs.BE_RELEASE_GITHUB_APP_NAME }}"
        git config user.email "${{ inputs.BE_RELEASE_GITHUB_APP_NAME }}@users.noreply.github.com"
        git config --global credential.helper store
        echo "https://x-access-token:${GITHUB_APP_TOKEN}@github.com" > ~/.git-credentials
